### ISSUE TITLE
Offline usage?

### ISSUE THREAD

**Issue by johnnytam100** [a-r-j/graphein#125]
Hi Arian! I'm sorry for opening an issue again but here is a feature request:
Is it possible to use graphein offline?
I am trying to run graphein in a supercomputer to perform massively parallel graph construction.
However, as you can expect, the nodes do not allow internet access so graphein ends up error like:

`urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>`

It will be nice if graphein can be used offline. :)

**Comment by a-r-j** [comment]
Is the problem with protein graphs?

If so, you’re in luck! Graphein can be used on local PDB files - I expect the part that is failing is the download from the PDB. If you use the `pdb_path` Parameter in [`construct_graph()`](https://graphein.ai/modules/graphein.protein.html#graphein.protein.graphs.construct_graph) you can simply provide a path to the PDB. Eg

```python
g = construct_graph(config=config, `pdb_path="../graphein/examples/pdbs/3eiy.pdb")
```

The only other thing that could fail as far as I can tell is if you’re downloading the pre-trained ESM model for extracting sequence embeddings.

I should also point out that we have a multiprocessing-based implementation in #73 to speed things up. It’s not in master yet, but if it’s a high priority for you I can bundle it in with the next minor update in the next few days.

**Comment by a-r-j** [comment]
Hi @johnnytam100 how did you get on? Can I close the issue?

**Comment by johnnytam100** [comment]
Hi Arian! I'm sorry for the late reply! I am testing it right now. Possibly you can close it first. :)
Thanks!!

**Comment by a-r-j** [comment]
Alright, let me know if you have some trouble. Happy to help! :)
