### ISSUE TITLE
Please fix construct_graph.py arguments

### ISSUE THREAD

**Issue by lerachel** [a-r-j/graphein#14]
Hi there,
Thank you for the very cool and useful package! I think on line 328 in construct_graph.py, you forgot to include `chain_selectio`n in your `dssp = self._get_protein_features()` argument.
It should be:
`dssp = self._get_protein_features(file_path=file_path, pdb_code=None, chain_selection=chain_selection)`

**Comment by a-r-j** [comment]
Thanks for spotting this @lerachel ! You are, of course, correct.This has been fixed now.
