### ISSUE TITLE
Support for small molecules & Protein Ligands

### ISSUE THREAD

**Issue by a-r-j** [a-r-j/graphein#155]
This issue serves as the starting point for developing features to support small molecule graphs.

### Ligands from Mol2 files:
* This should be straightforward using [BioPandas](https://github.com/rasbt/biopandas) support for Mol2 files: https://rasbt.github.io/biopandas/api_subpackages/biopandas.mol2/

### Ligands from SDF files
I'm not aware of any lightweight parsers for SDF files. We could use the parsers in OpenBabel/RDKit as optional dependencies, or lift the parsers from these libraries if they're sufficiently compact (and licensing is sufficiently permissive).

### Ligands from SMILES
Similar to the issues described for SDF files.

### Ligands from PDB Files
This should be straightforward to extract from the current PDB file parsing, we can extract them from the HETATM df, which is separated from the main polypeptide dataframe. The trickiness here comes from distinguishing cofactors/crystallographic adjuvants from 'true' ligands of interest. We could circumnavigate this by allowing users to remove typical species of these types - we maintain a dictionary of them [here](https://graphein.ai/modules/graphein.protein.html#graphein.protein.resi_atoms.COFACTOR_CODES)

### Inferring connectivity
Distance-based connectivity (eucl. threshold, KNN etc) should be straightforward and can likely leverage the existing code used for protein graphs. The more complicated scenario is inferring the covalent bonding from PDBs. PDB files may provide `CONNECT` records specifying ligand structure but I am not sure this is a guarantee. 

### Features
Some idea of the sorts of features users would like to use would be quite helpful. I think having RDKit as an optional dependency and allowing users to interact with it would be the most straightforward solution here.

Keen to hear thoughts :)

**Comment by yuanqidu** [comment]
Hey Arian, I will be working on it :D

**Comment by yuanqidu** [comment]
I agree that both RDKit and OpenBabel could be optionally dependency packages as they are much easier to install these days with conda and building the small molecule support with these two packages should be great.

**Comment by a-r-j** [comment]
Yep, I think of the two RDKit is the better choice since it is now [pip installable](https://pypi.org/project/rdkit-pypi/). OpenBabel could be trickier (I’ve had some issues getting the python bindings working properly in the past).
