### ISSUE TITLE
Unnecessary print statement

### ISSUE THREAD

**Issue by chrisyeh96** [a-r-j/graphein#166]
Could you please either comment out this print statement, or put it behind some verbosity flag? Thank you!

https://github.com/a-r-j/graphein/blob/6f6913a71aa2cab40d0b26b6e6bfbf7a2760a8fd/graphein/protein/edges/distance.py#L79

**Comment by a-r-j** [comment]
Thanks for tracking that down - it was getting on my nerves a little! Yep, will change this.
