### ISSUE TITLE
Upgrade compatibility to DGL 0.5.0+

### ISSUE THREAD

**Issue by a-r-j** [a-r-j/graphein#17]
Currently, Graphein is built with DGL 0.4.3

This throws an error: 

```File "d:\desktop2.0\prot\graphein\graphein\construct_graphs.py", line 23, in <module> from dgllife.utils import mol_to_bigraph, mol_to_complete_graph, mol_to_nearest_neighbor_graph File "D:\Anaconda\envs\myenv\lib\site-packages\dgllife\__init__.py", line 9, in <module> from . import model File "D:\Anaconda\envs\myenv\lib\site-packages\dgllife\model\__init__.py", line 8, in <module> from .model_zoo import * File "D:\Anaconda\envs\myenv\lib\site-packages\dgllife\model\model_zoo\__init__.py", line 33, in <module> from .acnn import * File "D:\Anaconda\envs\myenv\lib\site-packages\dgllife\model\model_zoo\acnn.py", line 14, in <module> from dgl import BatchedDGLHeteroGraph ImportError: cannot import name 'BatchedDGLHeteroGraph' from 'dgl' (D:\Anaconda\envs\myenv\lib\site-packages\dgl\__init__.py)```

See: https://github.com/dmlc/dgl/issues/2104

This has also been mentioned in #16

**Comment by mufeili** [comment]
I'm working on it. I think there might be some other compatibility issues as well and let me try to make a PR for graphein.

**Comment by a-r-j** [comment]
Thanks @mufeili that would be great!
