### ISSUE TITLE
Insertions always removed 

### ISSUE THREAD

**Issue by OliverT1** [a-r-j/graphein#173]
Even when changing config.insertions to True, insertions are always removed and not included as nodes in the generated graph.

This is due to the config.insertions paramater not being passed to process_dataframe() in graphs.py, meaning the default value of False is always used.

**Comment by a-r-j** [comment]
Thanks for the report and quick PR. 

Out of interest, what's your usecase here? I've considered adding support for an optional entrypoint to select insertions of interest though they've never been something I've wanted in practice.

**Comment by a-r-j** [comment]
Ah, I see; that makes sense.

That'd be great! Happy to discuss. I've just added a tutorial notebook appling e(n)GNNs to antibody developability prediction [here[(https://github.com/a-r-j/graphein/blob/rna3d/notebooks/tdc_developability.ipynb) that you might be interested in.

**Comment by OliverT1** [comment]
Great, I'll get in touch when I've wrapped up this project then. Thanks for sharing, very similar to what I'm doing! I'm also using the Satorras model.
