### ISSUE TITLE
AttributeError: Can't get attribute '_unpickle_block' on <module 'pandas._libs.internals' from '/usr/local/lib/python3.7/dist-packages/pandas/_libs/internals.cpython-37m-x86_64-linux-gnu.so'>

### ISSUE THREAD

**Issue by johnnytam100** [a-r-j/graphein#179]
Hi @a-r-j how are you doing? Sorry for raising a question again! 

Previously I prepared some protein graphs with graphein and I want to load them now.

```
! pip install graphein
! pip install pandas==1.1.5 

import glob
import pickle

# Load
filepath_list = []

for filepath in glob.iglob('../*.p'):
  filepath_list.append(filepath)

filepath_list.sort()

graph_list = []

for graph_path in filepath_list:

    # Load graph
    with open(graph_path, 'rb') as f:  # notice the r instead of w
        g_load = pickle.load(f)
```

And I got 

`AttributeError: Can't get attribute '_unpickle_block' on <module 'pandas._libs.internals' from '/usr/local/lib/python3.7/dist-packages/pandas/_libs/internals.cpython-37m-x86_64-linux-gnu.so'>`

According to [this thread](https://stackoverflow.com/questions/71090310/attributeerror-cant-get-attribute-unpickle-block),
it seems to be the problem with the version of pandas so I downgraded pandas from `1.3.5` to `1.1.5` but still didn't work.

Do you know what could be the possibilities?

I prepared the protein graphs with the graphein version dated around March 22, 2022.

**Comment by johnnytam100** [comment]
Unfortunately, my old environment has gone because I moved to a new lab.. 
To test if it is due to environment incompatibility, I have just re-prepared new graphs in a fresh new environment but still bump into the same error with `pickle.load`

Alternatively, do we have a different way of saving + loading graphein graphs?

After loading, I am doing machine learning downstream using `karateclub`, like this:

```
# Convert graph index to integer (required by karateclub)
g_load_reindex = nx.convert_node_labels_to_integers(g_load)
graph_list.append(g_load_reindex)

# Embedding
model = FeatherGraph()
model.fit(graph_list)
```

**Comment by a-r-j** [comment]
Hmm that's odd. I just tried a clean install on colab:


```python
#!pip install graphein
import pickle
import graphein.protein as gp
from graphein.testing.utils import graphs_equal 

g = gp.construct_graph(pdb_code="3eiy")

with open('filename.pickle', 'wb') as handle:
    pickle.dump(g, handle)

with open('filename.pickle', 'rb') as handle:
    b = pickle.load(handle)

print(graphs_equal(g, b)) # Returns True
```

**Comment by johnnytam100** [comment]
@a-r-j I am re-preparing new graphs so we can close this issue. :) THanks!
