### ISSUE TITLE
deprotonate pdb  structure

### ISSUE THREAD

**Issue by EyalRozenberg1** [a-r-j/graphein#198]
On Deprotonation process on the PDB file, I see that you choose to deprotonate the file according to 'atom_name' field rather than element_symbol field.

> see here: https://github.com/a-r-j/graphein/blob/553fd2615e69fcad74c6c2659b795faf6d1c798b/graphein/protein/graphs.py#L152

Is there a reason why not to deprotonate according to element_symbol?
Your approach lives some H atoms in the PDB file. I could not find any explanation why they are more important than those that were deprotonated.
Thanks

**Comment by a-r-j** [comment]
Thanks for the report, Eyal! Should be fixed in `1.5.1` :)
