### ISSUE TITLE
Missing Residue in resi_atoms.py

### ISSUE THREAD

**Issue by EyalRozenberg1** [a-r-j/graphein#200]
**Describe the bug**
MSE residue is missing in `RESI_NAMES`, `RESI_THREE_TO_1` at `graphein/protein/resi_atoms.py`

**To Reproduce**

1. Go to  > https://github.com/a-r-j/graphein/blob/553fd2615e69fcad74c6c2659b795faf6d1c798b/graphein/protein/resi_atoms.py
2. see 
>  https://github.com/a-r-j/graphein/blob/553fd2615e69fcad74c6c2659b795faf6d1c798b/graphein/protein/resi_atoms.py#L278
>  https://github.com/a-r-j/graphein/blob/553fd2615e69fcad74c6c2659b795faf6d1c798b/graphein/protein/resi_atoms.py#L372
3. Both are missing [MSE residue](https://www.ebi.ac.uk/pdbe-srv/pdbechem/chemicalCompound/show/MSE) 

**To solve**
Add `MSE` to `RESI_NAMES` and `MSE: M` to `RESI_THREE_TO_1`

best, Eyal

**Comment by a-r-j** [comment]
Thanks for the report, Eyal! Should be fixed in `1.5.1` :)
