### ISSUE TITLE
ImportError on Pytorch3d

### ISSUE THREAD

**Issue by jasonshi10** [a-r-j/graphein#22]
Hi Arian,

I followed the installation instructions on README and when I try to import the package ```from pytorch3d.io import load_obj, save_obj```I ran into the following error:

```
ImportError: dlopen(/Users/jason.shi/miniconda3/envs/graphein/lib/python3.7/site-packages/pytorch3d/_C.cpython-37m-darwin.so, 2): Symbol not found: __ZN2at23getLegacyDeviceTypeInitEv
  Referenced from: /Users/jason.shi/miniconda3/envs/graphein/lib/python3.7/site-packages/pytorch3d/_C.cpython-37m-darwin.so
  Expected in: /Users/jason.shi/miniconda3/envs/graphein/lib/python3.7/site-packages/torch/lib/libtorch_cpu.dylib
 in /Users/jason.shi/miniconda3/envs/graphein/lib/python3.7/site-packages/pytorch3d/_C.cpython-37m-darwin.so
```

I'm using torch 1.6.0 and installed on Mac laptop. Here's what I installed for torch geometric.

```
pip install torch-scatter==latest+cpu -f https://pytorch-geometric.com/whl/torch-1.6.0.html
pip install torch-sparse==latest+cpu -f https://pytorch-geometric.com/whl/torch-1.6.0.html
pip install torch-cluster==latest+cpu -f https://pytorch-geometric.com/whl/torch-1.6.0.html
pip install torch-spline-conv==latest+cpu -f https://pytorch-geometric.com/whl/torch-1.6.0.html
pip install torch-geometric
```

Would appreciate if you can point me to the right direction. Thanks!

**Comment by a-r-j** [comment]
Hi Jason, sorry to hear you’re having trouble. Could you give me some info on which pytorch3d version and build you’ve installed?

Thanks!

**Comment by a-r-j** [comment]
Hi again,

I realise now I’ve not included in the installation step for PyTorch 3D. Silly of me.

I think an uninstall of PyTorch 3D and a `pip install pytorch3d` should help things along. You can view the relevant docs [here].(https://github.com/facebookresearch/pytorch3d/blob/master/INSTALL.md). I believe if you try to conda install it on mac (which I’m guessing you’re on) it will try to install the CUDA build of PyTorch 3D.

Let me know if this helps.

 I’ll update the README asap. Thanks for pointing this out.

**Comment by jasonshi10** [comment]
Yes, I'm installing on a Mac (CPU). The pytorch3d version is 0.2.0. I did try to uninstall and re-install pytorch3d and didn't seem to resolve the issue.

**Comment by a-r-j** [comment]
Hmm 0.2.0 should work fine. It looks like a CUDA issue to me. Could you share the output of `conda list`?

**Comment by jasonshi10** [comment]
```
# Name                    Version                   Build  Channel
apbs                      1.5                  h1de35cc_3    schrodinger
appnope                   0.1.0                    pypi_0    pypi
argon2-cffi               20.1.0                   pypi_0    pypi
ase                       3.20.1                   pypi_0    pypi
async-generator           1.10                     pypi_0    pypi
attrs                     20.2.0                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
biopandas                 0.2.4                    pypi_0    pypi
biopython                 1.78             py37haf1e3a3_0  
blas                      1.0                         mkl  
bleach                    3.2.1                    pypi_0    pypi
boost                     1.68.0          py37h9888f84_1001    conda-forge
boost-cpp                 1.68.0            h6f8c590_1000    conda-forge
brotlipy                  0.7.0           py37haf1e3a3_1000  
bzip2                     1.0.8                h1de35cc_0  
ca-certificates           2020.6.20            hecda079_0    conda-forge
cairo                     1.16.0            h0ab9d94_1001    conda-forge
certifi                   2020.6.20        py37hc8dfbb8_0    conda-forge
cffi                      1.14.3           py37hed5b41f_0  
chardet                   3.0.4                 py37_1003  
cryptography              3.1.1            py37hddc9c9b_0  
curl                      7.71.1               hb0a8c7a_1  
cycler                    0.10.0                   py37_0  
cython                    0.29.21          py37hb1e8313_0  
dbus                      1.13.16              h18a8e69_0  
decorator                 4.4.2                      py_0  
defusedxml                0.6.0                    pypi_0    pypi
dgl                       0.4.3                    pypi_0    pypi
dgllife                   0.2.5                    py37_0    dglteam
dssp                      3.0.0                h0a44026_3    salilab
entrypoints               0.3                      pypi_0    pypi
expat                     2.2.9                hb1e8313_2  
fontconfig                2.13.1            h1027ab8_1000    conda-forge
freemol                   1.158                      py_2    schrodinger
freetype                  2.10.2               ha233b18_0  
future                    0.18.2                   pypi_0    pypi
fvcore                    0.1.2.post20200926            py_0    conda-forge
gettext                   0.19.8.1             hb0f4f8b_2  
glew                      2.0.0                         0    schrodinger
glib                      2.65.0               hc5f4afa_0  
googledrivedownloader     0.4                      pypi_0    pypi
graphein                  0.0.1                     dev_0    <develop>
h5py                      2.10.0           py37h3134771_0  
hdf4                      4.2.13               h39711bb_2  
hdf5                      1.10.4               hfa1e0ec_0  
icu                       58.2                 h0a44026_3  
idna                      2.10                       py_0  
importlib-metadata        2.0.0                    pypi_0    pypi
intel-openmp              2019.4                      233  
ipykernel                 5.3.4                    pypi_0    pypi
ipymol                    0.5                      pypi_0    pypi
ipython                   7.18.1                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                7.5.1                    pypi_0    pypi
isodate                   0.6.0                    pypi_0    pypi
jedi                      0.17.2                   pypi_0    pypi
jinja2                    2.11.2                   pypi_0    pypi
joblib                    0.16.0                     py_0  
jpeg                      9b                   he5867d9_2  
jsonschema                3.2.0                    pypi_0    pypi
jupyter                   1.0.0                    pypi_0    pypi
jupyter-client            6.1.7                    pypi_0    pypi
jupyter-console           6.2.0                    pypi_0    pypi
jupyter-core              4.6.3                    pypi_0    pypi
jupyterlab-pygments       0.1.1                    pypi_0    pypi
kiwisolver                1.2.0            py37h04f5b5a_0  
krb5                      1.18.2               h75d18d8_0  
lab                       6.1                      pypi_0    pypi
lcms2                     2.11                 h92f6f08_0  
libboost                  1.67.0               hebc422b_4  
libcurl                   7.71.1               h8a08a2b_1  
libcxx                    10.0.0                        1  
libedit                   3.1.20191231         h1de35cc_1  
libffi                    3.3                  hb1e8313_2  
libgfortran               3.0.1                h93005f0_2  
libholoplaycore           0.1.0_rc4                     0    schrodinger
libiconv                  1.16                 h1de35cc_0  
libnetcdf                 4.7.3                he3b6227_0  
libopenblas               0.3.10               h0794777_0  
libpng                    1.6.37               ha441bb4_0  
libssh2                   1.9.0                ha12b0ac_1  
libtiff                   4.1.0                hcb84e12_1  
libxml2                   2.9.10               h3b9e6c8_1  
llvm-openmp               10.0.0               h28b9765_0  
llvmlite                  0.34.0                   pypi_0    pypi
lz4-c                     1.9.2                hb1e8313_1  
markupsafe                1.1.1                    pypi_0    pypi
matplotlib                3.3.1                         0  
matplotlib-base           3.3.1            py37h181983e_0  
mengine                   1                    h1de35cc_1    schrodinger
mistune                   0.8.4                    pypi_0    pypi
mkl                       2019.4                      233  
mkl-service               2.3.0            py37hfbe908c_0  
mkl_fft                   1.2.0            py37hc64f4ea_0  
mkl_random                1.1.1            py37h959d312_0  
mpeg_encode               1                    h1de35cc_1    schrodinger
mtz2ccp4_px               1.0                  hdc02c5d_3    schrodinger
nbclient                  0.5.0                    pypi_0    pypi
nbconvert                 6.0.6                    pypi_0    pypi
nbformat                  5.0.7                    pypi_0    pypi
ncurses                   6.2                  h0a44026_1  
nest-asyncio              1.4.1                    pypi_0    pypi
networkx                  2.5                        py_0  
ninja                     1.10.1           py37h879752b_0  
notebook                  6.1.4                    pypi_0    pypi
numba                     0.51.2                   pypi_0    pypi
numpy                     1.19.1           py37h3b9f5b6_0  
numpy-base                1.19.1           py37hcfb5961_0  
olefile                   0.46                     py37_0  
openssl                   1.1.1h               haf1e3a3_0    conda-forge
packaging                 20.4                     pypi_0    pypi
pandas                    1.1.1            py37hb1e8313_0  
pandocfilters             1.4.2                    pypi_0    pypi
parso                     0.7.1                    pypi_0    pypi
pcre                      8.44                 hb1e8313_0  
pdb2pqr                   2.1.2+pymol                py_0    schrodinger
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    7.2.0            py37ha54b6ba_0  
pip                       20.2.2                   py37_0  
pixman                    0.38.0               h1de35cc_0  
pmw                       2.0.1+3                    py_3    schrodinger
portalocker               2.0.0                    pypi_0    pypi
prometheus-client         0.8.0                    pypi_0    pypi
prompt-toolkit            3.0.7                    pypi_0    pypi
ptyprocess                0.6.0                    pypi_0    pypi
pycairo                   1.19.1           py37h126230b_0  
pycparser                 2.20                       py_2  
pygments                  2.7.1                    pypi_0    pypi
pymol                     2.4.1            py37h92f0605_0    schrodinger
pyopenssl                 19.1.0                     py_1  
pyparsing                 2.4.7                      py_0  
pyqt                      5.9.2            py37h655552a_2  
pyrsistent                0.17.3                   pypi_0    pypi
pysocks                   1.7.1                    py37_0  
python                    3.7.9                h26836e1_0  
python-dateutil           2.8.1                      py_0  
python_abi                3.7                     1_cp37m    conda-forge
pytorch                   1.6.0                   py3.7_0    pytorch
pytorch3d                 0.2.0                    pypi_0    pypi
pytz                      2020.1                     py_0  
pyyaml                    5.3.1                    pypi_0    pypi
pyzmq                     19.0.2                   pypi_0    pypi
qt                        5.9.7                h468cd18_1  
qtconsole                 4.7.7                    pypi_0    pypi
qtpy                      1.9.0                    pypi_0    pypi
rdflib                    5.0.0                    pypi_0    pypi
rdkit                     2018.09.3        py37haff9cca_0    conda-forge
readline                  8.0                  h1de35cc_0  
requests                  2.24.0                     py_0  
rigimol                   1.3                           2    schrodinger
scikit-learn              0.23.2           py37h959d312_0  
scipy                     1.5.2            py37h912ce22_0  
seaborn                   0.11.0                     py_0  
send2trash                1.5.0                    pypi_0    pypi
setuptools                49.6.0                   py37_1  
simplejson                3.17.2                   pypi_0    pypi
sip                       4.19.8           py37h0a44026_0  
six                       1.15.0                     py_0  
sqlite                    3.33.0               hffcf06c_0  
tabulate                  0.8.7              pyh9f0ad1d_0    conda-forge
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.9.1                    pypi_0    pypi
testpath                  0.4.4                    pypi_0    pypi
threadpoolctl             2.1.0              pyh5ca1d4c_0  
ticc                      0.1.4                    pypi_0    pypi
tk                        8.6.10               hb0a8c7a_0  
torch-cluster             1.5.7                    pypi_0    pypi
torch-geometric           1.6.1                    pypi_0    pypi
torch-scatter             2.0.5                    pypi_0    pypi
torch-sparse              0.6.7                    pypi_0    pypi
torch-spline-conv         1.2.0                    pypi_0    pypi
torchvision               0.7.0                  py37_cpu    pytorch
tornado                   6.0.4            py37h1de35cc_1  
tqdm                      4.46.0                   pypi_0    pypi
traitlets                 5.0.4                    pypi_0    pypi
txt2tags                  3.7                      pypi_0    pypi
urllib3                   1.25.10                    py_0  
vmd-python                3.0.6            py37hcc20023_2    conda-forge
wcwidth                   0.2.5                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
wheel                     0.35.1                     py_0  
widgetsnbextension        3.5.1                    pypi_0    pypi
xz                        5.2.5                h1de35cc_0  
yacs                      0.1.8                    pypi_0    pypi
yaml                      0.2.5                haf1e3a3_0    conda-forge
zipp                      3.2.0                    pypi_0    pypi
zlib                      1.2.11               h1de35cc_3  
zstd                      1.4.5                h41d2c2f_0  
```

**Comment by a-r-j** [comment]
Hi Jason, 

Hopefully you've seen the response on your PyTorch 3D issue https://github.com/facebookresearch/pytorch3d/issues/377

Copying the response here for reference:

> Note that this issue and what I write here is mac specific.

pytorch3d has to be built for a particular version of pytorch. You are getting this error because of a mismatch between the version with which pytorch3d has been built and the version of pytorch (or one of them) you have in your environment.

If you are using the package from pypi (i.e. pip install pytorch3d) then there is only one right version of pytorch. The packages from latest version of pytorch3d (0.2.5) match the latest version of pytorch (1.6.0). The packages from version 0.2.0 of pytorch3d use pytorch 1.5.0.

**Comment by jasonshi10** [comment]
Hi Arian,

I used torch 1.5.0 and pytorch3d 0.2.0 and the import error has been resolved. Thank you!

**Comment by Arielbs** [comment]
Hi, I believe I have the same issue, I followed the steps above (macOS as well with no CUDA), torch 1.5.0 and torch3d 0.2.0 (I've also tried 1.6.0 and 0.2.5 with the same result) but I get the same error: RDKit is not installed, which is required for utils related to cheminformatics. Any chance I missing anything? 
Thanks


# Name                    Version                   Build  Channel
apbs                      1.5                  h1de35cc_3    schrodinger
appnope                   0.1.0                    pypi_0    pypi
ase                       3.20.1                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
biopandas                 0.2.4                    pypi_0    pypi
biopython                 1.78             py37h60d8a13_1    conda-forge
blas                      2.21                        mkl    conda-forge
boost                     1.68.0          py37h9888f84_1001    conda-forge
boost-cpp                 1.68.0            h6f8c590_1000    conda-forge
brotlipy                  0.7.0           py37h395d20d_1001    conda-forge
bzip2                     1.0.8                haf1e3a3_3    conda-forge
c-ares                    1.17.1               hc929b4f_0    conda-forge
ca-certificates           2020.11.8            h033912b_0    conda-forge
cached-property           1.5.2                    pypi_0    pypi
cairo                     1.16.0            h0ab9d94_1001    conda-forge
certifi                   2020.11.8        py37hf985489_0    conda-forge
cffi                      1.14.3           py37h446cb54_1    conda-forge
chardet                   3.0.4           py37h2987424_1008    conda-forge
cryptography              3.2.1            py37h3b7a55b_0    conda-forge
curl                      7.71.1               hcb81553_8    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cython                    0.29.21          py37h08f6e3d_1    conda-forge
dbus                      1.13.6               h0c50699_1    conda-forge
decorator                 4.4.2                      py_0    conda-forge
dgl                       0.4.3                    pypi_0    pypi
dgllife                   0.2.6                    py37_0    dglteam
dssp                      3.0.0                h0a44026_3    salilab
expat                     2.2.9                hb1e8313_2    conda-forge
fontconfig                2.13.1            h1027ab8_1000    conda-forge
freemol                   1.158                      py_2    schrodinger
freetype                  2.10.4               h3f75d11_0    conda-forge
future                    0.18.2                   pypi_0    pypi
fvcore                    0.1.2.post20201122          pypi_0    pypi
gettext                   0.19.8.1          haf92f58_1004    conda-forge
glew                      2.0.0                         0    schrodinger
glib                      2.66.3               h519c658_0    conda-forge
googledrivedownloader     0.4                      pypi_0    pypi
graphein                  0.0.1                     dev_0    <develop>
h5py                      3.1.0           nompi_py37h6dbf366_100    conda-forge
hdf4                      4.2.13            h84186c3_1003    conda-forge
hdf5                      1.10.6          nompi_h2ccf146_1110    conda-forge
icu                       58.2              h0a44026_1000    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
ipymol                    0.5                      pypi_0    pypi
ipython                   7.19.0                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
isodate                   0.6.0                    pypi_0    pypi
jedi                      0.17.2                   pypi_0    pypi
jinja2                    2.11.2                   pypi_0    pypi
joblib                    0.17.0                     py_0    conda-forge
jpeg                      9d                   hbcb3906_0    conda-forge
kiwisolver                1.3.1            py37h8ec247f_0    conda-forge
krb5                      1.17.2               h60d9502_0    conda-forge
lcms2                     2.11                 h11f7e16_1    conda-forge
libblas                   3.8.0                    21_mkl    conda-forge
libboost                  1.67.0               hebc422b_4
libcblas                  3.8.0                    21_mkl    conda-forge
libcurl                   7.71.1               h9bf37e3_8    conda-forge
libcxx                    11.0.0               h439d374_0    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libev                     4.33                 haf1e3a3_1    conda-forge
libffi                    3.2.1             hb1e8313_1007    conda-forge
libgfortran               5.0.0               h7cc5361_13    conda-forge
libgfortran5              9.3.0               h7cc5361_13    conda-forge
libglib                   2.66.3               h2575888_0    conda-forge
libholoplaycore           0.1.0_rc4                     0    schrodinger
libiconv                  1.16                 haf1e3a3_0    conda-forge
liblapack                 3.8.0                    21_mkl    conda-forge
liblapacke                3.8.0                    21_mkl    conda-forge
libnetcdf                 4.7.4           nompi_h4844aed_106    conda-forge
libnghttp2                1.41.0               h7580e61_2    conda-forge
libopenblas               0.3.12          openmp_h54245bb_1    conda-forge
libpng                    1.6.37               h7cec526_2    conda-forge
libssh2                   1.9.0                h8a08a2b_5    conda-forge
libtiff                   4.1.0                hca7d577_6    conda-forge
libwebp-base              1.1.0                hbcb3906_3    conda-forge
libxml2                   2.9.9                hd80cff7_2    conda-forge
llvm-openmp               11.0.0               h73239a0_1    conda-forge
llvmlite                  0.34.0                   pypi_0    pypi
lz4-c                     1.9.2                hb1e8313_3    conda-forge
markupsafe                1.1.1                    pypi_0    pypi
matplotlib                3.3.3            py37hf985489_0    conda-forge
matplotlib-base           3.3.3            py37hdacc966_0    conda-forge
mengine                   1                    h1de35cc_1    schrodinger
mkl                       2020.4             h08c4f10_301    conda-forge
mpeg_encode               1                    h1de35cc_1    schrodinger
mtz2ccp4_px               1.0                  hdc02c5d_3    schrodinger
ncurses                   6.2                  h2e338ed_4    conda-forge
networkx                  2.5                        py_0    conda-forge
ninja                     1.10.1               h445f430_2    conda-forge
numba                     0.51.2                   pypi_0    pypi
numpy                     1.19.4           py37h9ebeaaa_1    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openssl                   1.1.1h               haf1e3a3_0    conda-forge
pandas                    1.1.4            py37h9b0e0a3_0    conda-forge
parso                     0.7.1                    pypi_0    pypi
patsy                     0.5.1                      py_0    conda-forge
pcre                      8.44                 hb1e8313_0    conda-forge
pdb2pqr                   2.1.2+pymol                py_0    schrodinger
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    8.0.1            py37h09f51b7_0    conda-forge
pip                       20.2.4                     py_0    conda-forge
pixman                    0.38.0            h01d97ff_1003    conda-forge
pmw                       2.0.1+3                    py_3    schrodinger
portalocker               2.0.0                    pypi_0    pypi
prompt-toolkit            3.0.8                    pypi_0    pypi
ptyprocess                0.6.0                    pypi_0    pypi
pycairo                   1.20.0           py37ha7df449_1    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygments                  2.7.2                    pypi_0    pypi
pymol                     2.4.1            py37h92f0605_0    schrodinger
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.9.2            py37h2a560b1_4    conda-forge
pysocks                   1.7.1            py37h2987424_2    conda-forge
python                    3.7.8           h837cb1c_2_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pytorch                   1.5.0                   py3.7_0    pytorch
pytorch3d                 0.2.0                    pypi_0    pypi
pytz                      2020.4             pyhd8ed1ab_0    conda-forge
pyyaml                    5.3.1                    pypi_0    pypi
qt                        5.9.7                h93ee506_2    conda-forge
rdflib                    5.0.0                    pypi_0    pypi
rdkit                     2018.09.3        py37haff9cca_0    conda-forge
readline                  8.0                  h0678c8f_2    conda-forge
requests                  2.25.0             pyhd3deb0d_0    conda-forge
rigimol                   1.3                           2    schrodinger
scikit-learn              0.23.2           py37ha0250bc_3    conda-forge
scipy                     1.5.3            py37h821cff1_0    conda-forge
seaborn                   0.11.0               h694c41f_1    conda-forge
seaborn-base              0.11.0             pyhd8ed1ab_1    conda-forge
setuptools                49.6.0           py37h2987424_2    conda-forge
sip                       4.19.8           py37h0a44026_0
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.33.0               h960bd1c_1    conda-forge
statsmodels               0.12.1           py37h8ba3199_1    conda-forge
tabulate                  0.8.7                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
ticc                      0.1.4                    pypi_0    pypi
tk                        8.6.10               hb0a8c7a_1    conda-forge
torch-cluster             1.5.7                    pypi_0    pypi
torch-geometric           1.6.1                    pypi_0    pypi
torch-scatter             2.0.5                    pypi_0    pypi
torch-sparse              0.6.7                    pypi_0    pypi
torch-spline-conv         1.2.0                    pypi_0    pypi
torchvision               0.6.0                  py37_cpu    pytorch
tornado                   6.1              py37h4b544eb_0    conda-forge
tqdm                      4.46.0                   pypi_0    pypi
traitlets                 5.0.5                    pypi_0    pypi
urllib3                   1.26.2                   pypi_0    pypi
vmd-python                3.0.6            py37h992095b_5    conda-forge
wcwidth                   0.2.5                    pypi_0    pypi
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
yacs                      0.1.8                    pypi_0    pypi
zlib                      1.2.11            h7795811_1010    conda-forge
zstd                      1.4.5                h289c70a_2    conda-forge

**Comment by a-r-j** [comment]
Hi @Arielbs that looks to be DGL/DGL-LifeSci related rather than PyTorch3d related. I think this thread may be useful: https://github.com/awslabs/dgl-lifesci/issues/107

**Comment by Arielbs** [comment]
Thank you Arian, 
I found that I need explicitly import torch prior fo graphein functionalities for the rdkit to be recognized, it works now. 
Ariel

**Comment by a-r-j** [comment]
Great! Thanks for pointing that out, that's good to know. I hope Graphein proves useful. Please do let me know if you come across any issues or missing functionality that would be useful.
