### ISSUE TITLE
Quiet mode for loading protein models

### ISSUE THREAD

**Issue by davidfstein** [a-r-j/graphein#238]
**Is your feature request related to a problem? Please describe.**
My use case involves loading many proteins. Unfortunately, the progress meters displayed by graphein don't interact nicely with the messages or progress trackers I might choose to include when loading these proteins. 

**Describe the solution you'd like**
Add an optional quiet mode to construct_graph (e.g. verbose=0)

**Describe alternatives you've considered**
An alternative would be to remove the carriage returns so that the progress meters don't overwrite other printed info, but I think this would not be optimal.

**Additional context**
Happy to write a pull for this

**Comment by a-r-j** [comment]
Go ahead with the PR, I think this makes sense. Thanks for picking it up!
