### ISSUE TITLE
Create dictionary of non-standard amino acids

### ISSUE THREAD

**Issue by ericmjl** [a-r-j/graphein#25]
I had a quick look at the PDB file for `5E5T`. It seems they define the D-amino acids as HETATMS in the header:

```HETNAM     PHI IODO-PHENYLALANINE
HETNAM     DSN D-SERINE
HETNAM     DSG D-ASPARAGINE
HETNAM     DPN D-PHENYLALANINE
HETNAM     DCY D-CYSTEINE
HETNAM     DAS D-ASPARTIC ACID
HETNAM     DLY D-LYSINE
HETNAM     DLE D-LEUCINE
HETNAM     DAR D-ARGININE
HETNAM     DAL D-ALANINE
HETNAM     DTY D-TYROSINE
HETNAM     DIL D-ISOLEUCINE
HETNAM     DGL D-GLUTAMIC ACID
HETNAM     DVA D-VALINE
HETNAM     DPR D-PROLINE
HETNAM     DTH D-THREONINE
HETNAM     DHI D-HISTIDINE
HETNAM     FMT FORMIC ACID
HETNAM     EDO 1,2-ETHANEDIOL
HETSYN     EDO ETHYLENE GLYCOL
```

The PDB maintains a [list](http://ligand-expo.rcsb.org/ld-download.html) of chemical entities and their abbreviations so it should be a fairly straightforward lookup. Hopefully, these conventions are standard in practice. We'd probably want to label non-standard residues differently to the other hetatms in the dataframe to allow for more nuanced filtering E.g. keep non-standard residues but remove all the water molecules. In any case, I think we should probably keep one of those dictionaries in graphein for easy conversion between PDB ligand identifiers and SMILES/InCHI, though not a priority at this point.

On that page there's also a list of the PDB structures that contain each ligand which might be useful, though I'm not sure how regularly updated it is.

_Originally posted by @a-r-j in https://github.com/a-r-j/graphein/issues/19#issuecomment-703286314_

-----

Some things we can do:

- [ ] Add a source CSV file that gets loaded into a dictionary upon request.

**Comment by a-r-j** [comment]
I've added some mappings for non-standard amino acids from: https://www.globalphasing.com/buster/manual/maketnt/manual/lib_val/library_validation.html (+ a couple additions)

I'm not confident it's complete, but it should be enough to get us on track to deal with the vast majority of instances. Will be adding some scripts & data to use the resources from the PDB Ligand Expo: https://ligand-expo.rcsb.org/ld-download.html
