### ISSUE TITLE
visualize protein 3d structure in python scripts

### ISSUE THREAD

**Issue by pengzhangzhi** [a-r-j/graphein#256]
Hi. I found this tool can beautifully visualize the protein structure in jupyter notebook. I wonder if this can be implemented in python scripts.

**Comment by a-r-j** [comment]
Hi @pengzhangzhi, would you be able to share a bit more context about what you're trying to achieve?

For instance, the following script works:

```python
# example_plot.py

import graphein.protein as gp

if __name__ == "__main__":
    g = gp.construct_graph(pdb_code="3eiy")
    fig = gp.plotly_protein_structure_graph(g)
    fig.show()
```

**Comment by pengzhangzhi** [comment]
Hi @a-r-j ,thank you for the information. can the code save the figure? I want to visualize a whole bunch of pdbs and save them as images and then maybe convert them to videos. Since this tool can visualize beautiful protein structures, I want to implement this idea using your tool.

**Comment by a-r-j** [comment]
Yep!

You can save them as [HTML](https://plotly.com/python/interactive-html-export/) (maintains interactivity) and in [static](https://plotly.com/python/static-image-export/) format.

**Comment by pengzhangzhi** [comment]
Thank you for your helpful feedback! You are very nice!

**Comment by a-r-j** [comment]
Happy to help! :hugs:
