### ISSUE TITLE
Running graphein with pymol in parallel

### ISSUE THREAD

**Issue by OliviaViessmann** [a-r-j/graphein#261]
**Describe the bug**
I would like to run grapheins `create_mesh()` function in parallel on multiple workers. I assume that I need to spin up multiple pymol sessions `MolViewer()` for each worker specifying a dedicated `PORT`. However I am not sure how to set this from the "outside" -- this might actually be a feature request.

**To Reproduce**
trying to run something like
`Parallel(n_jobs = 8).it(create_mesh)(pdb) for pdb in pdbs`
This gets stuck if run naively. 

**Expected behavior**
Want to specify ports for each worker so that I can run pymol sessions on each of them

- OS: Ubuntu 20.04.4 LTS
- Python Version 3.8.16
- Graphein Version [e.g. 22] & how it was installed
  git pull + pip install, version: 1.5.2

**Comment by a-r-j** [comment]
Hi @OliviaViessmann I'm trying to take a look at this but I'm struggling to get Pytorch3d working on my dev machine. 

Did you run into any issues?

https://github.com/facebookresearch/pytorch3d/issues/1406

**Comment by a-r-j** [comment]
If you checkout the PR the ports should now be configurable by the `ProteinMeshConfig`. I suppose you could zip the configs with the relevant ports with the PDBs and pass them both as args to `create_mesh`.

**Comment by a-r-j** [comment]
Yep, I missed a spot!

**Comment by a-r-j** [comment]
Has this resolved the issue @OliviaViessmann? If so, I will merge the PR shortly.

Also, if you could share a short snippet I can turn into a test that would be super helpful :)

**Comment by a-r-j** [comment]
Thanks!! Hmm, I'll try to check it out this week. A quick heads up though: the config param added in #261 is `pymol_port` rather than `port`

**Comment by a-r-j** [comment]
I did some digging and this looks like a pymol limitation, rather than a graphein limitation:

https://github.com/schrodinger/pymol-open-source/blob/d0a3380636e3d4079a0320b372a330dcf797d660/modules/pymol/rpc.py#L23

We need to be able to set the port on the pymol listener and, sadly, we don't have easy access to it. Also, the max retries limits the number of servers you can run.

I suppose one way to go is to patch your local pymol install. You could for example set the port via an env var that pymol would read instead of the hardcoded `9123` and make the following modification to the Graphein viewer class:

```python
class MolViewer(object):
    def __init__(self, host=HOST, port=PORT):
        self.host = host
        self.port = int(port)
        self._process = None

    def __del__(self):
        self.stop()

    def __getattr__(self, key):
        if not self._process_is_running():
            self.start(["-cKQ"])

        return getattr(self._server, key)

    def _process_is_running(self):
        return self._process is not None and self._process.poll() is None

    def start(self, args=("-Q",), exe="pymol"):
        """Start the PyMOL RPC server and connect to it
        Start simple GUI (-xi), suppress all output (-Q):
            >>> viewer.start(["-xiQ"])
        Start headless (-cK), with some output (-q):
            >>> viewer.start(["-cKq"])
        """
        if self._process_is_running():
            print("A PyMOL RPC server is already running.")
            return

        assert isinstance(args, (list, tuple))



       ########################## CHANGE HERE


        env = os.environ.copy()
        env["PYMOL_XMLRPC_PORT"] = str(self.port)
        self._process = subprocess.Popen([exe, "-R"] + list(args), env=env)


       ########################## END CHANGE



        self._server = Server(uri="http://%s:%d/RPC2" % (self.host, self.port))

        # wait for the server
        while True:
            try:
                self._server.bg_color("white")
                break
            except IOError:
                time.sleep(0.1)

    def stop(self):
        if self._process_is_running():
            self._process.terminate()

    def display(self, width=0, height=0, ray=False, timeout=120):
        """Display PyMol session
        :param width: width in pixels (0 uses current viewport)
        :param height: height in pixels (0 uses current viewport)
        :param ray: use ray tracing (if running PyMOL headless, this parameter
        has no effect and ray tracing is always used)
        :param timeout: timeout in seconds
        Returns
        -------
        fig : IPython.display.Image
        """
        from IPython.display import Image, display
        from ipywidgets import IntProgress

        progress_max = int((timeout * 20) ** 0.5)
        progress = None
        filename = tempfile.mktemp(".png")

        try:
            self._server.png(filename, width, height, -1, int(ray))

            for i in range(1, progress_max):
                if os.path.exists(filename):
                    break

                if progress is None:
                    progress = IntProgress(min=0, max=progress_max)
                    display(progress)

                progress.value += 1
                time.sleep(i / 10.0)

            if not os.path.exists(filename):
                raise RuntimeError("timeout exceeded")

            return Image(filename)
        finally:
            if progress is not None:
                progress.close()

            try:
                os.unlink(filename)
            except:
                pass
```

Alternatively, I also came across [this](https://pymolwiki.org/index.php/XML-RPC_server) which seems to be a similar RPC component that reads from an env var.

**Comment by a-r-j** [comment]
Keen to hear how it goes :)
