### ISSUE TITLE
How to transform a surface to match original pdb reference frame

### ISSUE THREAD

**Issue by OliviaViessmann** [a-r-j/graphein#265]
**Describe the bug**
I am using `create_mesh()` to generate surfaces. The background pymol commands generates an `.obj`  which contains the vertices and faces, but it centers the protein, so the original pdb coordinates and the mesh do not align. How can I transform the surface vertices to match the original pdb reference frame?
After reading about the specific order of rotations and translations in pymol I adapted the `get_obj_file()` in graphein using a transformation command from the pymol Q&A before the `.obj` file is saved, but it doesn't do anything. I call the lines below after `pymol.load(pdb_file)` and before `pymol.save`
``` 
view = list(pymol.get_view())
M = view[0:3] + [-view[12]] + view[3:6] + [-view[13]] + view[6:9] + [-view[14]] + view[12:15] + [1.0]
pymol.transform_selection("(all)", M, 0, 0, 0, 1)
pymol.set_view([1, 0, 0, 0, 1, 0, 0, 0, 1] + view[9:])
```

**Expected behavior**
Does anyone have any ideas how I can align the pdb residue coordinates and the graphein vertex coordinates?

**Comment by a-r-j** [comment]
They came to me [in a dream](https://sourceforge.net/p/pymol/mailman/message/29543275/) :)
