### ISSUE TITLE
On `rgroup_df=compute_rgroup_dataframe(remove_insertions(raw_pdb_df))`

### ISSUE THREAD

**Issue by anton-bushuiev** [a-r-j/graphein#304]
Hi 👋!  

Is `remove_insertions` here on purpose or just a legacy part from the times when insertion codes were always removed?
https://github.com/a-r-j/graphein/blob/649a490505740a266b26976807e7f303c2a32ff0/graphein/protein/graphs.py#L540

Now it leads to an error, when running `add_beta_carbon_vector(g)` on any `g` with underlying insertions because `rgroup_df` does not contain beta carbons of inserted residues when the difference vectors are computed.

**Comment by a-r-j** [comment]
Good spot! Yep, this should be removed. I think now that insertion codes are part of residue IDs this shouldn't create any downstream problems.

**Comment by anton-bushuiev** [comment]
I found another related bug, so I'll make a PR
