### ISSUE TITLE
A small bug in the `creating_datasets_from_the_pdb.ipynb`

### ISSUE THREAD

**Issue by pengzhangzhi** [a-r-j/graphein#306]
Hi @amorehead and @a-r-j,

- I am playing with your PDBManager. It's really helpful!
- I found a subtle bug in the Jupyter notebook, https://colab.research.google.com/github/a-r-j/graphein/blob/master/notebooks/creating_datasets_from_the_pdb.ipynb?pli=1
You forget to first install `graphein` and then import it.

```bash
from rich import inspect
!pip install graphein
from graphein.ml.datasets import PDBManager

manager = PDBManager(root_dir=".")
inspect(manager, methods=True)
```

**Comment by a-r-j** [comment]
Thanks for spotting that! I will add it :)
