### ISSUE TITLE
Port DSSP Features to new API

### ISSUE THREAD

**Issue by a-r-j** [a-r-j/graphein#37]
This will take a little thought to do elegantly as the features are computed from sequence but assigned to nodes.

**Comment by cch1999** [comment]
Have added main DSSP functions to `dssp.py`. Set up PR #43.

Outstanding tasks are:

- [ ] Decide where and how to make the decision to run the DSSP program.
- [ ] Add pre-computing config to convert strings in the `secondary_structure` attribute to one hot encodings.
