### ISSUE TITLE
TypeError: construct_graph() got an unexpected keyword argument 'pdb_path'

### ISSUE THREAD

**Issue by zhaoxuetong** [a-r-j/graphein#389]
Dear ,

I got an error message:
from graphein.protein.graphs import construct_graph
g = construct_graph(config=config, pdb_path=str(protein_path)+str(pdb_ID)+".pdb")
TypeError: construct_graph() got an unexpected keyword argument 'pdb_path'

Can you take a look at the problem for me？Thanks for your patience.

Sincerely, 
Xuetong, Zhao

**Comment by a-r-j** [comment]
Hi @zhaoxuetong I believe the `pdb_path` argument has been renamed to `path`.

**Comment by zhaoxuetong** [comment]
Thank you for your patient help.
