### ISSUE TITLE
I can't use "graphein.protein.features.sequence.propy.aa_dipeptide_composition" to extract protein sequence features

### ISSUE THREAD

**Issue by Jrunchang** [a-r-j/graphein#414]
**Describe the bug**
when I construct the protein graph, a bug occur that ModuleNotFoundError: **No module named 'propy.AAComposition',**  **I don't know where to find the function AAComposition**
**from propy.AAComposition import CalculateAADipeptideComposition**

params_to_change = {"granularity": "CA","edge_construction_functions": [add_peptide_bonds],"node_metadata_functions": [meiler_embedding,expasy_protein_scale,amino_acid_one_hot,hydrogen_bond_acceptor,hydrogen_bond_donor,aa_dipeptide_composition]}#,,phi,psi,rsa,secondary_structure,add_beta_carbon_vector,add_sequence_neighbour_vector,add_sidechain_vector
config = ProteinGraphConfig(**params_to_change)
config.dict()
g = construct_graph(config= config,pdb_path=path)

**Screenshots**

**Desktop (please complete the following information):**

- Python Version
- Graphein Version1.4.0 & how it was installed: github package

**Comment by a-r-j** [comment]
Have you installed `propy`? `pip install propy3`

https://github.com/MartinThoma/propy3?tab=readme-ov-file

**Comment by Jrunchang** [comment]
Thank you for your reply, it works after I install propy3.
