### ISSUE TITLE
DGLError: Mutation is not supported in heterograph.

### ISSUE THREAD

**Issue by jadechip** [a-r-j/graphein#65]
Hi there,

When I try to run the protein graph example from the README I get the following error:
`DGLError: Mutation is not supported in heterograph.`

According this post If found on google: https://discuss.dgl.ai/t/how-to-add-nodes-edges-to-heterograph/696
adding nodes to heterographs is only supported in dgl > v0.5 but the installation instructions specify version 0.4.3.

Or am I missing something?

**Comment by a-r-j** [comment]
Hey @jadechip!

I recall we had some compatibility problems with DGL > 0.5 and so don't explitly support it. As for your error, that's a new error that I haven't come across - I suspect we may only support `dgl.DGLGraph`.

We've been working on a v2.0 of graphein (check it out on the `graphein-api` branch!) which I'd encourage you to use as there are many new features & we'll be sunsetting the version on `main` shortly.  There are some differences as we now build the graphs as networkx graphs and convert these into various geometric DL library formats with a convertor object (`graphein.ml.conversion` on the `conversion` branch. There are also a bunch of tutorial notebooks there in the `notebooks/` directory on this branch). We're a little light on docs at present but we expect to have everything wrapped this week :) If you have the time, it might make sense to hold off until next week - I don't expect any breaking changes but there'll be a fair bit of dev activity this week.

Happy to support via email too :)

Closing this as it's not related to 2.0
