### ISSUE TITLE
Saving in gexf format

### ISSUE THREAD

**Issue by shrimonmuke0202** [a-r-j/graphein#75]
An error occurs when saving protein atomic graph in gexf format. 

`attribute value type is not allowed: <class 'numpy.ndarray'>`

How can I overcome this problem?

**Comment by a-r-j** [comment]
Hi @shrimonmuke0202, gexf only supports a limited set of datatypes. You can check page 8 here: https://gephi.org/gexf/1.2draft/gexf-12draft-primer.pdf
