### ISSUE TITLE
Atom information

### ISSUE THREAD

**Issue by shrimonmuke0202** [a-r-j/graphein#76]
How can obtain the atoms, which are present in an atomic graph of a protein?

**Comment by a-r-j** [comment]
Hi @shrimonmuke0202, what exactly do you want to obtain from them? If you want access to the nodes you can do something like:


```python
for n, d in g.nodes(data=True):
    print(n)
    print(d)

```

Otherwise, the node data should be stored in the graph object as a dataframe:

```python
g.graph["pdb_df"]
```

**Comment by shrimonmuke0202** [comment]
I have a question, for a protein residue graph that has an empty edge list
but its atomic graph does not have an empty edge list? Also, the atom graph
has connections between two residues but in the residue graph, no
connection is present.
A:ARG:288:N A:CYS:287:C A:CYS:287:C A:CYS:287:O

**Comment by shrimonmuke0202** [comment]
PFA
Also, is the distance matrix in g.graph is contact matrix?

dist_mat': 0 1 2 0 0.000000 5.341208 12.412397 1 5.341208 0.000000 8.591149 2
12.412397 8.591149 0.000000}
