### ISSUE TITLE
Graphein Version Inconsistency?

### ISSUE THREAD

**Issue by chrisyeh96** [a-r-j/graphein#86]
In the setup.py file, the version is listed as 1.0.3:

https://github.com/a-r-j/graphein/blob/7c6b0792ec7e71e7fc26401cebfd2aeface6c794/setup.py#L137-L139

However, on PyPI, the current version for graphein is 1.0.6. What accounts for the difference in version numbers?

Also, is there a version history / changelog available anywhere? Thanks!

**Comment by a-r-j** [comment]
Hi @chrisyeh96 thanks for the bug reports. I'll have the two versions aligned tonight.

Re changelog, at present, no. That's a good point though, it's probably high time we kept one.
