### ISSUE TITLE
Odd Sklearn Dependency

### ISSUE THREAD

**Issue by chrisyeh96** [a-r-j/graphein#89]
The "base.in" file lists a "sklearn" dependency:

https://github.com/a-r-j/graphein/blob/f015e0f142f008054802ca39940eb18ac72a8d71/.requirements/base.in#L12

However, I think it should be "scikit-learn" instead of "sklearn." To my understanding, the package's name on PyPI and Conda is "scikit-learn," but for importing in actual python code, its name is "sklearn"

Oddly, there is an [actual package on PyPI called "sklearn"](https://pypi.org/project/sklearn/), which is why I think this mistake doesn't trigger any error message. But clearly, the sklearn (version 0.0) package is not the intended package.

**Comment by a-r-j** [comment]
Good spot! Thanks for flagging these issues :) Should be resolved in `1.0.9`
